### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "tes@tes.com",
  "password": "123456"
}

###

### CREATE USER
POST http://localhost:5000/add-user
Content-Type: application/json

{
  "name": "tes",
  "email": "tes@tess.com",
  "password": "123456"
}

###

### GET NOTES (harus pakai token dari login, ganti YOUR_ACCESS_TOKEN dengan token sebenarnya)

GET http://localhost:5000/note/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTE3VDE3OjEwOjQxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTE4VDEyOjI2OjUwLjAwMFoiLCJpYXQiOjE3NDc1NzEyNTcsImV4cCI6MTc0NzU3MTI4N30.FbVCN1s8Ba5BiC-sNWYYhpdsxDc0bvsVr9EvPl_gPU8


### Refresh Access Token
GET  http://localhost:5000/refresh-token
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTE3VDE3OjEwOjQxLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTE4VDExOjI0OjQ2LjAwMFoiLCJpYXQiOjE3NDc1Njc1NDksImV4cCI6MTc0NzY1Mzk0OX0.i2EM-PJ1Qpr5MLOEVZphoRZx7oVZyiSKKxlEUE6hpGs

